INSERT INTO ResumeTemplates (
  template_id,
  user_id,
  name,
  html_markup,
  css_styles,
  preview_image_url,
  sort_order
) VALUES
(
  'classic-column-01',
  NULL,
  'Classic Column',
  '<div class="template-shell tpl-classic-column"><aside class="template-sidebar"><h1>{{fullName}}</h1><p>{{email}}</p><p>{{phone}}</p><p>{{address}}</p><p>{{cityCountry}}</p><div class="template-links">{{links}}</div></aside><main class="template-main"><section class="template-section"><h2>Profile</h2><p>{{summary}}</p></section><section class="template-section"><h2>Experience</h2>{{experienceItems}}</section><section class="template-section"><h2>Education</h2>{{educationItems}}</section><section class="template-section"><h2>Skills</h2><div class="template-skill-list">{{skillItems}}</div></section></main></div>',
  '.template-shell.tpl-classic-column{display:grid;grid-template-columns:30% 70%;min-height:100%;background:#fffefc;color:#14211d;font-family:''Trebuchet MS'',sans-serif}.template-shell.tpl-classic-column .template-sidebar{padding:32px 24px;background:#0f766e;color:#f7fffd}.template-shell.tpl-classic-column .template-sidebar h1{margin:0 0 16px;font-size:2rem;letter-spacing:-.05em}.template-shell.tpl-classic-column .template-sidebar p{margin:0 0 8px;line-height:1.5}.template-shell.tpl-classic-column .template-main{padding:32px 28px}.template-shell.tpl-classic-column .template-section{margin-bottom:24px}.template-shell.tpl-classic-column .template-section h2{margin:0 0 12px;color:#0f766e;font-size:.95rem;letter-spacing:.12em;text-transform:uppercase}.template-shell.tpl-classic-column .template-entry{margin-bottom:14px;padding-bottom:14px;border-bottom:1px solid #d6e4df}.template-shell.tpl-classic-column .template-entry:last-child{border-bottom:0;margin-bottom:0;padding-bottom:0}.template-shell.tpl-classic-column .template-entry-top{display:flex;justify-content:space-between;gap:12px}.template-shell.tpl-classic-column .template-entry h3{margin:0 0 4px;font-size:1rem}.template-shell.tpl-classic-column .template-entry small{color:#5f766f}.template-shell.tpl-classic-column .template-entry p{margin:8px 0 0;line-height:1.6}.template-shell.tpl-classic-column .template-skill-list{display:flex;flex-wrap:wrap;gap:8px}.template-shell.tpl-classic-column .template-skill{padding:8px 12px;border-radius:999px;background:#ddf4ef;color:#115e59;font-weight:700}.template-shell.tpl-classic-column .template-link{display:inline-block;margin:6px 6px 0 0;padding:6px 10px;border-radius:999px;background:#ffffff20;color:#ffffff;font-size:.82rem}',
  '/assets/templates/classic-column-01-preview.png',
  1
),
(
  'midnight-slate-02',
  NULL,
  'Midnight Slate',
  '<div class="template-shell tpl-midnight-slate"><aside class="template-sidebar"><h1>{{fullName}}</h1><p>{{email}}</p><p>{{phone}}</p><p>{{address}}</p><p>{{cityCountry}}</p><div class="template-links">{{links}}</div></aside><main class="template-main"><section class="template-section"><h2>Profile</h2><p>{{summary}}</p></section><section class="template-section"><h2>Experience</h2>{{experienceItems}}</section><section class="template-section"><h2>Education</h2>{{educationItems}}</section><section class="template-section"><h2>Skills</h2><div class="template-skill-list">{{skillItems}}</div></section></main></div>',
  '.template-shell.tpl-midnight-slate{display:grid;grid-template-columns:34% 66%;min-height:100%;background:#f8fafc;color:#0f172a;font-family:Georgia,serif}.template-shell.tpl-midnight-slate .template-sidebar{padding:32px 24px;background:#1e293b;color:#e2e8f0}.template-shell.tpl-midnight-slate .template-sidebar h1{margin:0 0 16px;font-size:2rem;letter-spacing:-.05em}.template-shell.tpl-midnight-slate .template-sidebar p{margin:0 0 8px;line-height:1.5}.template-shell.tpl-midnight-slate .template-main{padding:32px 28px}.template-shell.tpl-midnight-slate .template-section{margin-bottom:24px}.template-shell.tpl-midnight-slate .template-section h2{margin:0 0 12px;color:#334155;font-size:.95rem;letter-spacing:.12em;text-transform:uppercase}.template-shell.tpl-midnight-slate .template-entry{margin-bottom:14px;padding-bottom:14px;border-bottom:1px solid #cbd5e1}.template-shell.tpl-midnight-slate .template-entry:last-child{border-bottom:0;margin-bottom:0;padding-bottom:0}.template-shell.tpl-midnight-slate .template-entry-top{display:flex;justify-content:space-between;gap:12px}.template-shell.tpl-midnight-slate .template-entry h3{margin:0 0 4px;font-size:1rem}.template-shell.tpl-midnight-slate .template-entry small{color:#64748b}.template-shell.tpl-midnight-slate .template-entry p{margin:8px 0 0;line-height:1.6}.template-shell.tpl-midnight-slate .template-skill-list{display:flex;flex-wrap:wrap;gap:8px}.template-shell.tpl-midnight-slate .template-skill{padding:8px 12px;border-radius:999px;background:#e2e8f0;color:#1e293b;font-weight:700}.template-shell.tpl-midnight-slate .template-link{display:inline-block;margin:6px 6px 0 0;padding:6px 10px;border-radius:999px;background:#ffffff12;color:#e2e8f0;font-size:.82rem}',
  '/assets/templates/midnight-slate-02-preview.png',
  2
),
(
  'sunrise-band-03',
  NULL,
  'Sunrise Band',
  '<div class="template-shell tpl-sunrise-band"><aside class="template-sidebar"><h1>{{fullName}}</h1><p>{{email}}</p><p>{{phone}}</p><p>{{address}}</p><p>{{cityCountry}}</p><div class="template-links">{{links}}</div></aside><main class="template-main"><section class="template-section"><h2>Profile</h2><p>{{summary}}</p></section><section class="template-section"><h2>Experience</h2>{{experienceItems}}</section><section class="template-section"><h2>Education</h2>{{educationItems}}</section><section class="template-section"><h2>Skills</h2><div class="template-skill-list">{{skillItems}}</div></section></main></div>',
  '.template-shell.tpl-sunrise-band{display:grid;grid-template-columns:28% 72%;min-height:100%;background:#fff7ed;color:#3b2f2f;font-family:''Segoe UI'',sans-serif}.template-shell.tpl-sunrise-band .template-sidebar{padding:32px 24px;background:#f97316;color:#fff7ed}.template-shell.tpl-sunrise-band .template-sidebar h1{margin:0 0 16px;font-size:2rem;letter-spacing:-.05em}.template-shell.tpl-sunrise-band .template-sidebar p{margin:0 0 8px;line-height:1.5}.template-shell.tpl-sunrise-band .template-main{padding:32px 28px}.template-shell.tpl-sunrise-band .template-section{margin-bottom:24px}.template-shell.tpl-sunrise-band .template-section h2{margin:0 0 12px;color:#ea580c;font-size:.95rem;letter-spacing:.12em;text-transform:uppercase}.template-shell.tpl-sunrise-band .template-entry{margin-bottom:14px;padding-bottom:14px;border-bottom:1px solid #fed7aa}.template-shell.tpl-sunrise-band .template-entry:last-child{border-bottom:0;margin-bottom:0;padding-bottom:0}.template-shell.tpl-sunrise-band .template-entry-top{display:flex;justify-content:space-between;gap:12px}.template-shell.tpl-sunrise-band .template-entry h3{margin:0 0 4px;font-size:1rem}.template-shell.tpl-sunrise-band .template-entry small{color:#9a6b49}.template-shell.tpl-sunrise-band .template-entry p{margin:8px 0 0;line-height:1.6}.template-shell.tpl-sunrise-band .template-skill-list{display:flex;flex-wrap:wrap;gap:8px}.template-shell.tpl-sunrise-band .template-skill{padding:8px 12px;border-radius:999px;background:#ffedd5;color:#9a3412;font-weight:700}.template-shell.tpl-sunrise-band .template-link{display:inline-block;margin:6px 6px 0 0;padding:6px 10px;border-radius:999px;background:#ffffff20;color:#fff7ed;font-size:.82rem}',
  '/assets/templates/sunrise-band-03-preview.png',
  3
),
(
  'forest-profile-04',
  NULL,
  'Forest Profile',
  '<div class="template-shell tpl-forest-profile"><aside class="template-sidebar"><h1>{{fullName}}</h1><p>{{email}}</p><p>{{phone}}</p><p>{{address}}</p><p>{{cityCountry}}</p><div class="template-links">{{links}}</div></aside><main class="template-main"><section class="template-section"><h2>Profile</h2><p>{{summary}}</p></section><section class="template-section"><h2>Experience</h2>{{experienceItems}}</section><section class="template-section"><h2>Education</h2>{{educationItems}}</section><section class="template-section"><h2>Skills</h2><div class="template-skill-list">{{skillItems}}</div></section></main></div>',
  '.template-shell.tpl-forest-profile{display:grid;grid-template-columns:32% 68%;min-height:100%;background:#f0fdf4;color:#163021;font-family:''Aptos'',sans-serif}.template-shell.tpl-forest-profile .template-sidebar{padding:32px 24px;background:#166534;color:#f0fdf4}.template-shell.tpl-forest-profile .template-sidebar h1{margin:0 0 16px;font-size:2rem;letter-spacing:-.05em}.template-shell.tpl-forest-profile .template-sidebar p{margin:0 0 8px;line-height:1.5}.template-shell.tpl-forest-profile .template-main{padding:32px 28px}.template-shell.tpl-forest-profile .template-section{margin-bottom:24px}.template-shell.tpl-forest-profile .template-section h2{margin:0 0 12px;color:#15803d;font-size:.95rem;letter-spacing:.12em;text-transform:uppercase}.template-shell.tpl-forest-profile .template-entry{margin-bottom:14px;padding-bottom:14px;border-bottom:1px solid #bbf7d0}.template-shell.tpl-forest-profile .template-entry:last-child{border-bottom:0;margin-bottom:0;padding-bottom:0}.template-shell.tpl-forest-profile .template-entry-top{display:flex;justify-content:space-between;gap:12px}.template-shell.tpl-forest-profile .template-entry h3{margin:0 0 4px;font-size:1rem}.template-shell.tpl-forest-profile .template-entry small{color:#4d7c5a}.template-shell.tpl-forest-profile .template-entry p{margin:8px 0 0;line-height:1.6}.template-shell.tpl-forest-profile .template-skill-list{display:flex;flex-wrap:wrap;gap:8px}.template-shell.tpl-forest-profile .template-skill{padding:8px 12px;border-radius:999px;background:#dcfce7;color:#166534;font-weight:700}.template-shell.tpl-forest-profile .template-link{display:inline-block;margin:6px 6px 0 0;padding:6px 10px;border-radius:999px;background:#ffffff1f;color:#f0fdf4;font-size:.82rem}',
  '/assets/templates/forest-profile-04-preview.png',
  4
),
(
  'royal-edge-05',
  NULL,
  'Royal Edge',
  '<div class="template-shell tpl-royal-edge"><aside class="template-sidebar"><h1>{{fullName}}</h1><p>{{email}}</p><p>{{phone}}</p><p>{{address}}</p><p>{{cityCountry}}</p><div class="template-links">{{links}}</div></aside><main class="template-main"><section class="template-section"><h2>Profile</h2><p>{{summary}}</p></section><section class="template-section"><h2>Experience</h2>{{experienceItems}}</section><section class="template-section"><h2>Education</h2>{{educationItems}}</section><section class="template-section"><h2>Skills</h2><div class="template-skill-list">{{skillItems}}</div></section></main></div>',
  '.template-shell.tpl-royal-edge{display:grid;grid-template-columns:35% 65%;min-height:100%;background:#faf5ff;color:#2e1065;font-family:''Cambria'',serif}.template-shell.tpl-royal-edge .template-sidebar{padding:32px 24px;background:#6d28d9;color:#f5f3ff}.template-shell.tpl-royal-edge .template-sidebar h1{margin:0 0 16px;font-size:2rem;letter-spacing:-.05em}.template-shell.tpl-royal-edge .template-sidebar p{margin:0 0 8px;line-height:1.5}.template-shell.tpl-royal-edge .template-main{padding:32px 28px}.template-shell.tpl-royal-edge .template-section{margin-bottom:24px}.template-shell.tpl-royal-edge .template-section h2{margin:0 0 12px;color:#7c3aed;font-size:.95rem;letter-spacing:.12em;text-transform:uppercase}.template-shell.tpl-royal-edge .template-entry{margin-bottom:14px;padding-bottom:14px;border-bottom:1px solid #ddd6fe}.template-shell.tpl-royal-edge .template-entry:last-child{border-bottom:0;margin-bottom:0;padding-bottom:0}.template-shell.tpl-royal-edge .template-entry-top{display:flex;justify-content:space-between;gap:12px}.template-shell.tpl-royal-edge .template-entry h3{margin:0 0 4px;font-size:1rem}.template-shell.tpl-royal-edge .template-entry small{color:#7e6aa8}.template-shell.tpl-royal-edge .template-entry p{margin:8px 0 0;line-height:1.6}.template-shell.tpl-royal-edge .template-skill-list{display:flex;flex-wrap:wrap;gap:8px}.template-shell.tpl-royal-edge .template-skill{padding:8px 12px;border-radius:999px;background:#ede9fe;color:#5b21b6;font-weight:700}.template-shell.tpl-royal-edge .template-link{display:inline-block;margin:6px 6px 0 0;padding:6px 10px;border-radius:999px;background:#ffffff1a;color:#f5f3ff;font-size:.82rem}',
  '/assets/templates/royal-edge-05-preview.png',
  5
),
(
  'charcoal-line-06',
  NULL,
  'Charcoal Line',
  '<div class="template-shell tpl-charcoal-line"><aside class="template-sidebar"><h1>{{fullName}}</h1><p>{{email}}</p><p>{{phone}}</p><p>{{address}}</p><p>{{cityCountry}}</p><div class="template-links">{{links}}</div></aside><main class="template-main"><section class="template-section"><h2>Profile</h2><p>{{summary}}</p></section><section class="template-section"><h2>Experience</h2>{{experienceItems}}</section><section class="template-section"><h2>Education</h2>{{educationItems}}</section><section class="template-section"><h2>Skills</h2><div class="template-skill-list">{{skillItems}}</div></section></main></div>',
  '.template-shell.tpl-charcoal-line{display:grid;grid-template-columns:26% 74%;min-height:100%;background:#f8fafc;color:#111827;font-family:''Arial'',sans-serif}.template-shell.tpl-charcoal-line .template-sidebar{padding:32px 24px;background:#111827;color:#f9fafb}.template-shell.tpl-charcoal-line .template-sidebar h1{margin:0 0 16px;font-size:2rem;letter-spacing:-.05em}.template-shell.tpl-charcoal-line .template-sidebar p{margin:0 0 8px;line-height:1.5}.template-shell.tpl-charcoal-line .template-main{padding:32px 28px}.template-shell.tpl-charcoal-line .template-section{margin-bottom:24px}.template-shell.tpl-charcoal-line .template-section h2{margin:0 0 12px;color:#374151;font-size:.95rem;letter-spacing:.12em;text-transform:uppercase}.template-shell.tpl-charcoal-line .template-entry{margin-bottom:14px;padding-bottom:14px;border-bottom:1px solid #d1d5db}.template-shell.tpl-charcoal-line .template-entry:last-child{border-bottom:0;margin-bottom:0;padding-bottom:0}.template-shell.tpl-charcoal-line .template-entry-top{display:flex;justify-content:space-between;gap:12px}.template-shell.tpl-charcoal-line .template-entry h3{margin:0 0 4px;font-size:1rem}.template-shell.tpl-charcoal-line .template-entry small{color:#6b7280}.template-shell.tpl-charcoal-line .template-entry p{margin:8px 0 0;line-height:1.6}.template-shell.tpl-charcoal-line .template-skill-list{display:flex;flex-wrap:wrap;gap:8px}.template-shell.tpl-charcoal-line .template-skill{padding:8px 12px;border-radius:999px;background:#e5e7eb;color:#111827;font-weight:700}.template-shell.tpl-charcoal-line .template-link{display:inline-block;margin:6px 6px 0 0;padding:6px 10px;border-radius:999px;background:#ffffff14;color:#f9fafb;font-size:.82rem}',
  '/assets/templates/charcoal-line-06-preview.png',
  6
),
(
  'berry-glass-07',
  NULL,
  'Berry Glass',
  '<div class="template-shell tpl-berry-glass"><aside class="template-sidebar"><h1>{{fullName}}</h1><p>{{email}}</p><p>{{phone}}</p><p>{{address}}</p><p>{{cityCountry}}</p><div class="template-links">{{links}}</div></aside><main class="template-main"><section class="template-section"><h2>Profile</h2><p>{{summary}}</p></section><section class="template-section"><h2>Experience</h2>{{experienceItems}}</section><section class="template-section"><h2>Education</h2>{{educationItems}}</section><section class="template-section"><h2>Skills</h2><div class="template-skill-list">{{skillItems}}</div></section></main></div>',
  '.template-shell.tpl-berry-glass{display:grid;grid-template-columns:31% 69%;min-height:100%;background:#fff1f2;color:#4c0519;font-family:''Calibri'',sans-serif}.template-shell.tpl-berry-glass .template-sidebar{padding:32px 24px;background:#be123c;color:#fff1f2}.template-shell.tpl-berry-glass .template-sidebar h1{margin:0 0 16px;font-size:2rem;letter-spacing:-.05em}.template-shell.tpl-berry-glass .template-sidebar p{margin:0 0 8px;line-height:1.5}.template-shell.tpl-berry-glass .template-main{padding:32px 28px}.template-shell.tpl-berry-glass .template-section{margin-bottom:24px}.template-shell.tpl-berry-glass .template-section h2{margin:0 0 12px;color:#e11d48;font-size:.95rem;letter-spacing:.12em;text-transform:uppercase}.template-shell.tpl-berry-glass .template-entry{margin-bottom:14px;padding-bottom:14px;border-bottom:1px solid #fecdd3}.template-shell.tpl-berry-glass .template-entry:last-child{border-bottom:0;margin-bottom:0;padding-bottom:0}.template-shell.tpl-berry-glass .template-entry-top{display:flex;justify-content:space-between;gap:12px}.template-shell.tpl-berry-glass .template-entry h3{margin:0 0 4px;font-size:1rem}.template-shell.tpl-berry-glass .template-entry small{color:#9f5467}.template-shell.tpl-berry-glass .template-entry p{margin:8px 0 0;line-height:1.6}.template-shell.tpl-berry-glass .template-skill-list{display:flex;flex-wrap:wrap;gap:8px}.template-shell.tpl-berry-glass .template-skill{padding:8px 12px;border-radius:999px;background:#ffe4e6;color:#9f1239;font-weight:700}.template-shell.tpl-berry-glass .template-link{display:inline-block;margin:6px 6px 0 0;padding:6px 10px;border-radius:999px;background:#ffffff1c;color:#fff1f2;font-size:.82rem}',
  '/assets/templates/berry-glass-07-preview.png',
  7
),
(
  'ocean-grid-08',
  NULL,
  'Ocean Grid',
  '<div class="template-shell tpl-ocean-grid"><aside class="template-sidebar"><h1>{{fullName}}</h1><p>{{email}}</p><p>{{phone}}</p><p>{{address}}</p><p>{{cityCountry}}</p><div class="template-links">{{links}}</div></aside><main class="template-main"><section class="template-section"><h2>Profile</h2><p>{{summary}}</p></section><section class="template-section"><h2>Experience</h2>{{experienceItems}}</section><section class="template-section"><h2>Education</h2>{{educationItems}}</section><section class="template-section"><h2>Skills</h2><div class="template-skill-list">{{skillItems}}</div></section></main></div>',
  '.template-shell.tpl-ocean-grid{display:grid;grid-template-columns:29% 71%;min-height:100%;background:#eff6ff;color:#172554;font-family:''Verdana'',sans-serif}.template-shell.tpl-ocean-grid .template-sidebar{padding:32px 24px;background:#1d4ed8;color:#eff6ff}.template-shell.tpl-ocean-grid .template-sidebar h1{margin:0 0 16px;font-size:2rem;letter-spacing:-.05em}.template-shell.tpl-ocean-grid .template-sidebar p{margin:0 0 8px;line-height:1.5}.template-shell.tpl-ocean-grid .template-main{padding:32px 28px}.template-shell.tpl-ocean-grid .template-section{margin-bottom:24px}.template-shell.tpl-ocean-grid .template-section h2{margin:0 0 12px;color:#2563eb;font-size:.95rem;letter-spacing:.12em;text-transform:uppercase}.template-shell.tpl-ocean-grid .template-entry{margin-bottom:14px;padding-bottom:14px;border-bottom:1px solid #bfdbfe}.template-shell.tpl-ocean-grid .template-entry:last-child{border-bottom:0;margin-bottom:0;padding-bottom:0}.template-shell.tpl-ocean-grid .template-entry-top{display:flex;justify-content:space-between;gap:12px}.template-shell.tpl-ocean-grid .template-entry h3{margin:0 0 4px;font-size:1rem}.template-shell.tpl-ocean-grid .template-entry small{color:#5b73b3}.template-shell.tpl-ocean-grid .template-entry p{margin:8px 0 0;line-height:1.6}.template-shell.tpl-ocean-grid .template-skill-list{display:flex;flex-wrap:wrap;gap:8px}.template-shell.tpl-ocean-grid .template-skill{padding:8px 12px;border-radius:999px;background:#dbeafe;color:#1d4ed8;font-weight:700}.template-shell.tpl-ocean-grid .template-link{display:inline-block;margin:6px 6px 0 0;padding:6px 10px;border-radius:999px;background:#ffffff1e;color:#eff6ff;font-size:.82rem}',
  '/assets/templates/ocean-grid-08-preview.png',
  8
),
(
  'sandstone-pro-09',
  NULL,
  'Sandstone Pro',
  '<div class="template-shell tpl-sandstone-pro"><aside class="template-sidebar"><h1>{{fullName}}</h1><p>{{email}}</p><p>{{phone}}</p><p>{{address}}</p><p>{{cityCountry}}</p><div class="template-links">{{links}}</div></aside><main class="template-main"><section class="template-section"><h2>Profile</h2><p>{{summary}}</p></section><section class="template-section"><h2>Experience</h2>{{experienceItems}}</section><section class="template-section"><h2>Education</h2>{{educationItems}}</section><section class="template-section"><h2>Skills</h2><div class="template-skill-list">{{skillItems}}</div></section></main></div>',
  '.template-shell.tpl-sandstone-pro{display:grid;grid-template-columns:33% 67%;min-height:100%;background:#fffbeb;color:#422006;font-family:''Book Antiqua'',serif}.template-shell.tpl-sandstone-pro .template-sidebar{padding:32px 24px;background:#a16207;color:#fffbeb}.template-shell.tpl-sandstone-pro .template-sidebar h1{margin:0 0 16px;font-size:2rem;letter-spacing:-.05em}.template-shell.tpl-sandstone-pro .template-sidebar p{margin:0 0 8px;line-height:1.5}.template-shell.tpl-sandstone-pro .template-main{padding:32px 28px}.template-shell.tpl-sandstone-pro .template-section{margin-bottom:24px}.template-shell.tpl-sandstone-pro .template-section h2{margin:0 0 12px;color:#ca8a04;font-size:.95rem;letter-spacing:.12em;text-transform:uppercase}.template-shell.tpl-sandstone-pro .template-entry{margin-bottom:14px;padding-bottom:14px;border-bottom:1px solid #fde68a}.template-shell.tpl-sandstone-pro .template-entry:last-child{border-bottom:0;margin-bottom:0;padding-bottom:0}.template-shell.tpl-sandstone-pro .template-entry-top{display:flex;justify-content:space-between;gap:12px}.template-shell.tpl-sandstone-pro .template-entry h3{margin:0 0 4px;font-size:1rem}.template-shell.tpl-sandstone-pro .template-entry small{color:#8d6b2e}.template-shell.tpl-sandstone-pro .template-entry p{margin:8px 0 0;line-height:1.6}.template-shell.tpl-sandstone-pro .template-skill-list{display:flex;flex-wrap:wrap;gap:8px}.template-shell.tpl-sandstone-pro .template-skill{padding:8px 12px;border-radius:999px;background:#fef3c7;color:#92400e;font-weight:700}.template-shell.tpl-sandstone-pro .template-link{display:inline-block;margin:6px 6px 0 0;padding:6px 10px;border-radius:999px;background:#ffffff1e;color:#fffbeb;font-size:.82rem}',
  '/assets/templates/sandstone-pro-09-preview.png',
  9
),
(
  'mono-lite-10',
  NULL,
  'Mono Lite',
  '<div class="template-shell tpl-mono-lite"><aside class="template-sidebar"><h1>{{fullName}}</h1><p>{{email}}</p><p>{{phone}}</p><p>{{address}}</p><p>{{cityCountry}}</p><div class="template-links">{{links}}</div></aside><main class="template-main"><section class="template-section"><h2>Profile</h2><p>{{summary}}</p></section><section class="template-section"><h2>Experience</h2>{{experienceItems}}</section><section class="template-section"><h2>Education</h2>{{educationItems}}</section><section class="template-section"><h2>Skills</h2><div class="template-skill-list">{{skillItems}}</div></section></main></div>',
  '.template-shell.tpl-mono-lite{display:grid;grid-template-columns:27% 73%;min-height:100%;background:#fafafa;color:#171717;font-family:''Courier New'',monospace}.template-shell.tpl-mono-lite .template-sidebar{padding:32px 24px;background:#525252;color:#fafafa}.template-shell.tpl-mono-lite .template-sidebar h1{margin:0 0 16px;font-size:2rem;letter-spacing:-.05em}.template-shell.tpl-mono-lite .template-sidebar p{margin:0 0 8px;line-height:1.5}.template-shell.tpl-mono-lite .template-main{padding:32px 28px}.template-shell.tpl-mono-lite .template-section{margin-bottom:24px}.template-shell.tpl-mono-lite .template-section h2{margin:0 0 12px;color:#404040;font-size:.95rem;letter-spacing:.12em;text-transform:uppercase}.template-shell.tpl-mono-lite .template-entry{margin-bottom:14px;padding-bottom:14px;border-bottom:1px solid #d4d4d4}.template-shell.tpl-mono-lite .template-entry:last-child{border-bottom:0;margin-bottom:0;padding-bottom:0}.template-shell.tpl-mono-lite .template-entry-top{display:flex;justify-content:space-between;gap:12px}.template-shell.tpl-mono-lite .template-entry h3{margin:0 0 4px;font-size:1rem}.template-shell.tpl-mono-lite .template-entry small{color:#737373}.template-shell.tpl-mono-lite .template-entry p{margin:8px 0 0;line-height:1.6}.template-shell.tpl-mono-lite .template-skill-list{display:flex;flex-wrap:wrap;gap:8px}.template-shell.tpl-mono-lite .template-skill{padding:8px 12px;border-radius:999px;background:#e5e5e5;color:#262626;font-weight:700}.template-shell.tpl-mono-lite .template-link{display:inline-block;margin:6px 6px 0 0;padding:6px 10px;border-radius:999px;background:#ffffff18;color:#fafafa;font-size:.82rem}',
  '/assets/templates/mono-lite-10-preview.png',
  10
)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  html_markup = VALUES(html_markup),
  css_styles = VALUES(css_styles),
  preview_image_url = VALUES(preview_image_url),
  sort_order = VALUES(sort_order);
